
---
- name: My Playbook Includes
  hosts: all
  become: yes

  vars:
   mytext: "Privet ot Roman S"

  tasks:
  - name: Ping test
    ping:

  - include: create_folders.yml
  - include: create_files.yml mytext="Hello from Poltava"



