---
- name: Install Apache and upload MyWebPage
  hosts: all
  become: yes


  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html


  tasks:
  - name: Check and Print linux Version.
    debug: var=ansible_os_family

  - block:    #Block for RedHat
     - name: Install Apache webserver for RedHat
       yum: name=httpd state=latest

     - name: Copy MyHomePage to Servers
       copy: src={{ source_file }} dest={{ destin_file }} mode=0555
       notify: Restart apache RedHat

     - name: Start WebServer service for RedHat
       service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block:    #Block for Ubuntu

     - name: Install Apache webserver for Debian
       apt: name=apache2 state=latest

     - name: Copy MyHomePage to Servers
       copy: src={{ source_file }} dest={{ destin_file }} mode=0555
       notify: Restart apache

     - name: Start WebServer service for Debian
       service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"


  handlers:
  - name: Restart Apache Debian
    service: name=apache2 state=restarted

  - name: Restart Apache RedHat
    service: name=httpd state=restarted
